# Generated by Django 4.1.5 on 2023-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.CharField(max_length=5)),
                ('suit', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'cards_52_carddeck',
            },
        ),
    ]
